### ISSUE TITLE
Definir idea principal.

### ISSUE THREAD

**Issue by StealthSignatures** [StealthSignatures/project-desing#1]
Lluvia de ideas acerca del proyecto.

**Comment by LUGTER23** [comment]
Juego NFT

**Comment by StealthSignatures** [comment]
- Market Place(NFTs)
- RPG On-Chain(Cartas, Por turnos)

**Comment by StealthSignatures** [comment]
Enfocarse en proyectos NTF. Buscar ejemplos y correrlos en entorno local.
